AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact

DotPosition:
  EnforcedStyle: trailing

RescueModifier:
  Enabled: false
