default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: <%= ENV["PG_USER_NAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "" %>

development:
  <<: *default
  database: stormtroopers_development

test:
  <<: *default
  database: stormtroopers_test
